Fixed typo from tailData.totalDifficulty.lt(1) to tailData.totalDifficulty.lte(1)
Typo causes "PeerChannel: Error while processing 'block' message. TypeError: tailData.totalDifficulty.lt is not a function" when trying to reach consensus in light mode starting with block height = 1